### ISSUE TITLE
List several improvements or tutorials on how to edit the decomp

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [YohannDR/mzm#27]
like pokeemerald
where you can replace the engine with that high quality audio mixer
https://github.com/ipatix/gba-hq-mixer/tree/main

**Comment by YohannDR** [comment]
Can you clarify which one you mean exactly?
- How to edit the decomp for personal/hacking use
- How to edit the decomp to improve the codebase, documentation...

I'm assuming it's the first one, but I just want to be sure

**Comment by H-A-M-G-E-R** [comment]
the first one, for fixing several vanilla bugs

**Comment by YohannDR** [comment]
In this case, i'd rather do something similar to the [pokeemerald expansion](https://github.com/rh-hideout/pokeemerald-expansion), keeping the original decomp and the "hackable" version different.

**Comment by H-A-M-G-E-R** [comment]
Yeah, like Project ZM.

**Comment by H-A-M-G-E-R** [comment]
also i don't like discord anymore... now i use revolt.chat from now on.
